"""资产基础设施：文件存储、签名 URL、散列与 Range 文件服务。"""

from . import asset_store
from .asset_store import (
    ImagePixelLimitError,
    UnsupportedImageFormatError,
    action_pose_asset_path,
    action_source_asset_path,
    build_data_uri,
    client_asset_url,
    compute_file_sha256,
    dated_asset_directory,
    delete_user_assets,
    image_chain_asset_path,
    image_mime_for_extension,
    normalize_asset_reference,
    outfit_asset_directory,
    pack_asset_directory,
    parse_companion_asset_path,
    read_asset_data_uri,
    resolve_asset_reference,
    resolve_companion_asset_path,
    save_action_pose_asset_async,
    save_action_source_asset_async,
    save_companion_asset,
    save_companion_asset_async,
    save_image_chain_asset_async,
    save_video_job_asset_async,
    scene_asset_directory,
    signed_companion_asset_url,
    sniff_media_ext,
    unlink_companion_asset,
    validate_image_bytes,
    verify_signed_asset_request,
    video_job_asset_path,
)
from .http_range import serve_ranged_file
from .media_download import VIDEO_DOWNLOAD_ATTEMPTS, download_media_result
from .write_protection import (
    asset_write_context,
    asset_write_in_progress,
    forget_asset_write,
    protect_asset_write,
    prune_completed_asset_writes,
    user_asset_lock,
)

__all__ = [
    "asset_write_context",
    "asset_write_in_progress",
    "forget_asset_write",
    "protect_asset_write",
    "prune_completed_asset_writes",
    "user_asset_lock",
    "ImagePixelLimitError",
    "UnsupportedImageFormatError",
    "VIDEO_DOWNLOAD_ATTEMPTS",
    "download_media_result",
    "action_pose_asset_path",
    "save_action_pose_asset_async",
    "action_source_asset_path",
    "save_action_source_asset_async",
    "asset_store",
    "dated_asset_directory",
    "outfit_asset_directory",
    "pack_asset_directory",
    "scene_asset_directory",
    "build_data_uri",
    "image_mime_for_extension",
    "normalize_asset_reference",
    "read_asset_data_uri",
    "resolve_asset_reference",
    "client_asset_url",
    "compute_file_sha256",
    "delete_user_assets",
    "parse_companion_asset_path",
    "resolve_companion_asset_path",
    "save_companion_asset",
    "save_companion_asset_async",
    "save_video_job_asset_async",
    "image_chain_asset_path",
    "save_image_chain_asset_async",
    "serve_ranged_file",
    "signed_companion_asset_url",
    "video_job_asset_path",
    "sniff_media_ext",
    "unlink_companion_asset",
    "validate_image_bytes",
    "verify_signed_asset_request",
]
