import { useStore } from '@nanostores/react'

import { $locale } from '@/shared/store/locale'

const zh = {
  title: '桌面',
  chat: '对话',
  posts: '动态',
  diary: '日记',
  scene: '场景',
  appearance: '外观',
  channels: '消息渠道',
  settings: '设置',
  whisper: '轻语',
  showWhisper: '展开轻语',
  hideWhisper: '收起轻语',
  leftWhisper: '移到左侧',
  rightWhisper: '移到右侧',
  companion: '伙伴',
  companionAlwaysOnTop: '精灵置顶',
  showCompanion: '显示伙伴',
  hideCompanion: '隐藏伙伴',
  resizeCompanion: '调整伙伴大小',
  windowMode: '返回窗口模式',
  display: '交互显示器',
  accounts: '账户',
  addAccount: '添加账户',
  quit: '退出唤生',
  dock: '程序 Dock',
  pinnedApps: '固定程序',
  runningApps: '运行中的程序',
  running: '正在运行',
  pinApp: '固定到 Dock',
  unpinApp: '取消固定',
  cannotPin: '无法识别启动目标，请从应用列表选择',
  minimizedWindow: '已最小化',
  runningUnavailable: '运行程序列表暂时不可用',
  addApp: '添加程序',
  repairApp: '重新选择程序',
  moveLeft: '向左移动',
  moveRight: '向右移动',
  missing: '程序不可用，请重新选择程序',
  dockHint: '从已安装应用中选择程序，拖入程序或快捷方式也可添加',
  pickAdd: '添加程序',
  pickRepair: '重新选择程序',
  pickSearch: '搜索程序名称',
  pickLoading: '正在读取应用…',
  pickLoadFailed: '应用列表读取失败，可重新扫描',
  pickEmpty: '没有找到匹配的程序',
  pickBrowse: '浏览文件…',
  pickCancel: '取消',
  pickAdded: '已添加',
  pickRescan: '重新扫描',
  pickSources: {
    'start-user': '开始菜单',
    'start-all': '所有用户开始菜单',
    'desktop-user': '桌面',
    'desktop-onedrive': 'OneDrive 桌面',
    'desktop-public': '公共桌面',
    'app-paths': '已登记程序',
    'apps-folder': 'Windows 应用'
  },
  pickSourceFailed: '以下位置未能读取',
  minimize: '最小化',
  maximize: '最大化',
  restore: '还原',
  close: '关闭',
  resize: '调整窗口大小',
  switcher: '打开的窗口',
  loading: '正在连接…',
  connected: '已连接',
  disconnected: '连接中断',
  accountLoading: '正在读取账户…',
  retry: '重试',
  desktopSettings: '桌面设置',
  disturbance: '陪伴方式',
  still: '静止',
  normal: '常规',
  autonomous: '自主',
  waiting: '正在准备桌面…'
}

const en: typeof zh = {
  title: 'Desktop',
  chat: 'Chat',
  posts: 'Posts',
  diary: 'Diary',
  scene: 'Scenes',
  appearance: 'Appearance',
  channels: 'Channels',
  settings: 'Settings',
  whisper: 'Whisper',
  showWhisper: 'Show whisper',
  hideWhisper: 'Collapse whisper',
  leftWhisper: 'Move to left',
  rightWhisper: 'Move to right',
  companion: 'Companion',
  companionAlwaysOnTop: 'Keep companion on top',
  showCompanion: 'Show companion',
  hideCompanion: 'Hide companion',
  resizeCompanion: 'Resize companion',
  windowMode: 'Return to window mode',
  display: 'Interactive display',
  accounts: 'Accounts',
  addAccount: 'Add account',
  quit: 'Quit SpiritAgent',
  dock: 'App Dock',
  pinnedApps: 'Pinned apps',
  runningApps: 'Running apps',
  running: 'Running',
  pinApp: 'Pin to Dock',
  unpinApp: 'Unpin from Dock',
  cannotPin: 'Launch target unavailable; select the app from the app list',
  minimizedWindow: 'Minimized',
  runningUnavailable: 'Running apps are temporarily unavailable',
  addApp: 'Add app',
  repairApp: 'Choose app again',
  moveLeft: 'Move left',
  moveRight: 'Move right',
  missing: 'App unavailable. Choose it again.',
  dockHint: 'Pick an installed app, or drop an app or shortcut onto the Dock',
  pickAdd: 'Add app',
  pickRepair: 'Choose app again',
  pickSearch: 'Search apps',
  pickLoading: 'Reading apps…',
  pickLoadFailed: 'Could not read apps. Rescan to retry.',
  pickEmpty: 'No matching app',
  pickBrowse: 'Browse files…',
  pickCancel: 'Cancel',
  pickAdded: 'Added',
  pickRescan: 'Rescan',
  pickSources: {
    'start-user': 'Start menu',
    'start-all': 'All users start menu',
    'desktop-user': 'Desktop',
    'desktop-onedrive': 'OneDrive desktop',
    'desktop-public': 'Public desktop',
    'app-paths': 'Registered apps',
    'apps-folder': 'Windows apps'
  },
  pickSourceFailed: 'Could not read',
  minimize: 'Minimize',
  maximize: 'Maximize',
  restore: 'Restore',
  close: 'Close',
  resize: 'Resize window',
  switcher: 'Open windows',
  loading: 'Connecting…',
  connected: 'Connected',
  disconnected: 'Disconnected',
  accountLoading: 'Loading accounts…',
  retry: 'Retry',
  desktopSettings: 'Desktop settings',
  disturbance: 'Companionship',
  still: 'Still',
  normal: 'Normal',
  autonomous: 'Autonomous',
  waiting: 'Preparing desktop…'
}

export function useDesktopStrings(): typeof zh {
  return useStore($locale) === 'en' ? en : zh
}
