import { useStore } from '@nanostores/react'

import { $locale } from '@/shared/store/locale'

const zh = {
  title: '桌面',
  chat: '对话',
  posts: '动态',
  diary: '日记',
  scene: '场景',
  appearance: '外观',
  channels: '消息渠道',
  settings: '设置',
  station: '工作环境',
  whisper: '轻语',
  showWhisper: '展开轻语',
  hideWhisper: '收起轻语',
  leftWhisper: '移到左侧',
  rightWhisper: '移到右侧',
  companion: '伙伴',
  showCompanion: '显示伙伴',
  hideCompanion: '隐藏伙伴',
  resizeCompanion: '调整伙伴大小',
  windowMode: '返回窗口模式',
  display: '交互显示器',
  accounts: '账户',
  addAccount: '添加账户',
  quit: '退出唤生',
  dock: '常用程序',
  addApp: '添加程序',
  repairApp: '重新选择程序',
  removeApp: '移除',
  moveLeft: '向左移动',
  moveRight: '向右移动',
  missing: '程序不可用，请重新选择程序',
  dockHint: '拖入程序或快捷方式，添加到 Dock',
  minimize: '最小化',
  maximize: '最大化',
  restore: '还原',
  close: '关闭',
  resize: '调整窗口大小',
  switcher: '打开的窗口',
  loading: '正在连接…',
  connected: '已连接',
  disconnected: '连接中断',
  accountLoading: '正在读取账户…',
  retry: '重试',
  desktopSettings: '桌面设置',
  disturbance: '陪伴方式',
  still: '静止',
  normal: '常规',
  autonomous: '自主',
  livingSettings: '生活设置',
  waiting: '正在准备桌面…'
}

const en: typeof zh = {
  title: 'Desktop',
  chat: 'Chat',
  posts: 'Posts',
  diary: 'Diary',
  scene: 'Scenes',
  appearance: 'Appearance',
  channels: 'Channels',
  settings: 'Settings',
  station: 'Workspace',
  whisper: 'Whisper',
  showWhisper: 'Show whisper',
  hideWhisper: 'Collapse whisper',
  leftWhisper: 'Move to left',
  rightWhisper: 'Move to right',
  companion: 'Companion',
  showCompanion: 'Show companion',
  hideCompanion: 'Hide companion',
  resizeCompanion: 'Resize companion',
  windowMode: 'Return to window mode',
  display: 'Interactive display',
  accounts: 'Accounts',
  addAccount: 'Add account',
  quit: 'Quit SpiritAgent',
  dock: 'Favorite apps',
  addApp: 'Add app',
  repairApp: 'Choose app again',
  removeApp: 'Remove',
  moveLeft: 'Move left',
  moveRight: 'Move right',
  missing: 'App unavailable. Choose it again.',
  dockHint: 'Drop an app or shortcut to add it to the Dock',
  minimize: 'Minimize',
  maximize: 'Maximize',
  restore: 'Restore',
  close: 'Close',
  resize: 'Resize window',
  switcher: 'Open windows',
  loading: 'Connecting…',
  connected: 'Connected',
  disconnected: 'Disconnected',
  accountLoading: 'Loading accounts…',
  retry: 'Retry',
  desktopSettings: 'Desktop settings',
  disturbance: 'Companionship',
  still: 'Still',
  normal: 'Normal',
  autonomous: 'Autonomous',
  livingSettings: 'Life settings',
  waiting: 'Preparing desktop…'
}

export function useDesktopStrings(): typeof zh {
  return useStore($locale) === 'en' ? en : zh
}
