from . import (
    gemini,  # noqa: F401 — 副作用：注册 gemini 供应商
    grok,  # noqa: F401 — 副作用：注册 grok 供应商
    mimo,  # noqa: F401 — 副作用：注册 mimo 供应商
    minimax,  # noqa: F401 — 副作用：注册 minimax 供应商
    zhipu,  # noqa: F401 — 副作用：注册 zhipu 供应商
)
from ._reference import resolve_reference_bytes
from .base import (
    AudioChunk,
    BaseProvider,
    ChatProvider,
    EmbeddingProvider,
    ImageAsset,
    ImageGenProvider,
    ImageGenRequest,
    ImageGenResult,
    ProviderConfig,
    ProviderError,
    ProviderResultUnknownError,
    ServiceType,
    STTProvider,
    STTResult,
    TTSProvider,
    TTSResult,
    VideoAsset,
    VideoGenProvider,
    VideoGenRequest,
    VideoJobStatus,
    VoiceDesignResult,
)
from .http import aclose_all, rotate_http_clients
from .mimo import (
    MiMoChatProvider,
    MiMoImageGenProvider,
    MiMoSTTProvider,
    MiMoTTSProvider,
)
from .registry import (
    OPENAI_COMPATIBLE_PROVIDERS,
    PROVIDER_DEFAULT_URLS,
    default_base_url,
    default_context_tokens_for,
    default_model_for,
    default_video_model_for,
    default_vision_model_for,
    providers_supporting,
    register,
    resolve,
    resolve_context_tokens,
    supports_video,
    supports_vision,
    try_resolve,
)

__all__ = [
    "OPENAI_COMPATIBLE_PROVIDERS",
    "PROVIDER_DEFAULT_URLS",
    "AudioChunk",
    "BaseProvider",
    "ChatProvider",
    "EmbeddingProvider",
    "ImageAsset",
    "ImageGenProvider",
    "ImageGenRequest",
    "ImageGenResult",
    "MiMoChatProvider",
    "MiMoImageGenProvider",
    "MiMoSTTProvider",
    "MiMoTTSProvider",
    "ProviderConfig",
    "ProviderError",
    "ProviderResultUnknownError",
    "STTProvider",
    "STTResult",
    "ServiceType",
    "TTSProvider",
    "TTSResult",
    "VideoAsset",
    "VideoGenProvider",
    "VideoGenRequest",
    "VideoJobStatus",
    "VoiceDesignResult",
    "aclose_all",
    "default_base_url",
    "default_context_tokens_for",
    "default_model_for",
    "default_video_model_for",
    "default_vision_model_for",
    "providers_supporting",
    "register",
    "resolve",
    "resolve_context_tokens",
    "resolve_reference_bytes",
    "rotate_http_clients",
    "supports_video",
    "supports_vision",
    "try_resolve",
]
