"""生成应用流程：形象、外观、场景与媒体生成的生命周期编排。"""

from .appearance_prompts import (
    build_avatar_reference_prompt,
    build_image_edit_prompt,
    build_outfit_prompt,
    describe_character_form,
    describe_garment_image,
    enhance_avatar_prompt,
)
from .avatar_service import (
    ALLOWED_AVATAR_UPLOAD_MIME_TYPES,
    AvatarGenerationError,
    AvatarNotFoundError,
    AvatarSourceUnreadableError,
    FullbodyGenerationError,
    ImageSealedError,
    accept_fullbody_candidate,
    adopt_avatar_seed,
    adopt_fullbody_seed,
    confirm_fullbody_seed,
    finalize_avatar,
    generate_avatar,
    generate_fullbody_reference,
    get_active_avatar,
    get_avatar_job_lock,
    latest_fullbody_candidate,
    list_avatar_history,
    prepare_avatar_prompt,
    prepare_fullbody_prompt,
    raise_if_image_sealed,
    regenerate_avatar,
    regenerate_avatar_from_image,
    retry_fullbody_candidate_analysis,
    select_avatar,
)
from .character_card import (
    drain_character_extractions,
    resume_character_extractions,
    resume_user_character_extraction,
    schedule_character_extraction,
)
from .character_images import generate_character_images
from .chat_images import ImageBatch, generate_chat_images, inspect_chat_image, regenerate_chat_image
from .image_generation import (
    ImageGenerationError,
    generate_images,
    resolve_image_gen_chain,
)
from .initial_appearance import resume_initial_appearance
from .media_review import (
    MediaReviewStateError,
    accept_media_review,
    get_media_review,
    has_pending_action_review,
    list_pending_media_reviews,
    reject_media_review,
    reject_pending_action_reviews,
)
from .outfit_service import (
    OutfitDraftExpiredError,
    OutfitError,
    OutfitNotFoundError,
    OutfitStateError,
    activate_outfit,
    adopt_outfit_draft_image,
    adopt_outfit_regenerate_image,
    confirm_outfit,
    create_outfit_draft,
    delete_outfit,
    drain_outfit_descriptions,
    get_outfit_policy,
    list_outfits,
    prepare_outfit_prompt,
    prepare_outfit_regenerate_prompt,
    recover_outfit_descriptions,
    regenerate_outfit_draft,
    retry_outfit_description,
    set_outfit_policy,
)
from .paid_work import GenerationWorkPaused, require_new_generation_call, require_video_generation_call
from .response_builders import (
    avatar_response,
    outfit_response,
)
from .scene_service import (
    SceneError,
    SceneNotFoundError,
    SceneStateError,
    activate_scene,
    adopt_scene,
    delete_scene,
    discard_scene,
    drain_scene_jobs,
    edit_scene_description,
    regenerate_scene,
    resume_scene_generation,
    resume_scene_jobs,
    resume_user_scene_jobs,
    retry_scene_description,
    scene_generation_wait_seconds,
    schedule_scene_generation,
    schedule_scene_prompt,
    set_scene_policy,
)
from .video import (
    VideoPackError,
    VideoPackNotFoundError,
    VideoPackStateError,
    kick_dynamic_action,
    list_pack_responses,
    load_pack_response,
    require_action_matting_model,
    require_pack_generation_identity,
    resume_user_dynamic_actions,
    resume_video_generation_jobs,
)
from .video import (
    activate_pack as activate_video_pack,
)
from .video import (
    create_pack_from_clips as create_video_pack_from_clips,
)
from .video import (
    create_pack_from_reference as create_video_pack_from_reference,
)
from .video import (
    delete_pack as delete_video_pack,
)
from .video import drain_video_generation as drain_video_pack_generation
from .video import ensure_system_action as ensure_video_system_action
from .video import (
    retry_pack as retry_video_pack,
)
from .video_jobs import (
    discard_post_video_job,
    enqueue_video_job,
    ensure_video_capability,
    get_job,
    post_video_asset,
    post_video_ready,
    query_post_video_job,
    resume_pending_video_jobs,
    resume_user_video_jobs,
    select_video_resolution,
    video_generation_wait_seconds,
)
from .video_jobs import drain as drain_video_jobs
from .visual_identity import (
    apply_outfit_override,
    build_self_image_prompt,
    build_self_video_prompt,
    load_self_visual_context,
    optional_outfit_image_reference,
    prepare_self_video_reference,
)

__all__ = [
    "GenerationWorkPaused",
    "require_new_generation_call",
    "require_video_generation_call",
    "require_action_matting_model",
    "require_pack_generation_identity",
    "build_avatar_reference_prompt",
    "build_image_edit_prompt",
    "build_outfit_prompt",
    "describe_character_form",
    "describe_garment_image",
    "enhance_avatar_prompt",
    "ImageBatch",
    "generate_chat_images",
    "inspect_chat_image",
    "regenerate_chat_image",
    "build_self_image_prompt",
    "build_self_video_prompt",
    "SceneError",
    "SceneNotFoundError",
    "SceneStateError",
    "activate_scene",
    "adopt_scene",
    "delete_scene",
    "discard_scene",
    "drain_scene_jobs",
    "edit_scene_description",
    "regenerate_scene",
    "retry_scene_description",
    "resume_scene_generation",
    "resume_scene_jobs",
    "resume_user_scene_jobs",
    "resume_user_character_extraction",
    "schedule_scene_generation",
    "schedule_scene_prompt",
    "set_scene_policy",
    "load_self_visual_context",
    "optional_outfit_image_reference",
    "prepare_self_video_reference",
    "apply_outfit_override",
    "drain_character_extractions",
    "resume_character_extractions",
    "schedule_character_extraction",
    "resume_initial_appearance",
    "ALLOWED_AVATAR_UPLOAD_MIME_TYPES",
    "AvatarGenerationError",
    "accept_fullbody_candidate",
    "accept_media_review",
    "get_media_review",
    "has_pending_action_review",
    "list_pending_media_reviews",
    "reject_media_review",
    "reject_pending_action_reviews",
    "MediaReviewStateError",
    "latest_fullbody_candidate",
    "retry_fullbody_candidate_analysis",
    "AvatarNotFoundError",
    "AvatarSourceUnreadableError",
    "FullbodyGenerationError",
    "VideoPackError",
    "VideoPackNotFoundError",
    "VideoPackStateError",
    "ImageGenerationError",
    "ImageSealedError",
    "OutfitDraftExpiredError",
    "OutfitError",
    "OutfitNotFoundError",
    "OutfitStateError",
    "activate_video_pack",
    "create_video_pack_from_clips",
    "create_video_pack_from_reference",
    "ensure_video_system_action",
    "kick_dynamic_action",
    "retry_video_pack",
    "delete_video_pack",
    "list_pack_responses",
    "load_pack_response",
    "activate_outfit",
    "adopt_fullbody_seed",
    "adopt_avatar_seed",
    "prepare_avatar_prompt",
    "adopt_outfit_draft_image",
    "adopt_outfit_regenerate_image",
    "avatar_response",
    "confirm_fullbody_seed",
    "confirm_outfit",
    "create_outfit_draft",
    "delete_outfit",
    "drain_outfit_descriptions",
    "drain_video_jobs",
    "drain_video_pack_generation",
    "enqueue_video_job",
    "discard_post_video_job",
    "post_video_asset",
    "post_video_ready",
    "query_post_video_job",
    "resume_user_video_jobs",
    "ensure_video_capability",
    "finalize_avatar",
    "generate_avatar",
    "generate_fullbody_reference",
    "generate_images",
    "generate_character_images",
    "scene_generation_wait_seconds",
    "video_generation_wait_seconds",
    "get_active_avatar",
    "get_avatar_job_lock",
    "get_job",
    "get_outfit_policy",
    "list_avatar_history",
    "list_outfits",
    "outfit_response",
    "prepare_fullbody_prompt",
    "prepare_outfit_prompt",
    "prepare_outfit_regenerate_prompt",
    "raise_if_image_sealed",
    "regenerate_avatar",
    "regenerate_avatar_from_image",
    "regenerate_outfit_draft",
    "recover_outfit_descriptions",
    "retry_outfit_description",
    "resolve_image_gen_chain",
    "resume_pending_video_jobs",
    "resume_user_dynamic_actions",
    "resume_video_generation_jobs",
    "select_avatar",
    "select_video_resolution",
    "set_outfit_policy",
]
