"""生成应用流程：形象、外观、场景与媒体生成的生命周期编排。"""

from .avatar_service import (
    ALLOWED_AVATAR_UPLOAD_MIME_TYPES,
    AVATAR_JOB_LOCKS,
    AvatarGenerationError,
    AvatarNotFoundError,
    AvatarSourceUnreadableError,
    FullbodyGenerationError,
    ImageSealedError,
    adopt_avatar_seed,
    adopt_fullbody_seed,
    confirm_fullbody_seed,
    delete_portrait_file,
    finalize_avatar,
    generate_avatar,
    generate_fullbody_reference,
    get_active_avatar,
    get_avatar_job_lock,
    list_avatar_history,
    load_avatar_bytes_as_data_uri,
    normalize_avatar_url_to_bare,
    prepare_avatar_prompt,
    prepare_fullbody_prompt,
    raise_if_image_sealed,
    re_sign_bare_path,
    regenerate_avatar,
    regenerate_avatar_from_image,
    resolve_uploaded_avatar_path,
    select_avatar,
)
from .character_card import drain_character_extractions, resume_character_extractions, schedule_character_extraction
from .image_generation import (
    ImageGenerationError,
    compose_image_references,
    generate_images,
    resolve_image_gen_chain,
)
from .initial_appearance import resume_initial_appearance
from .outfit_service import (
    OutfitDraftExpiredError,
    OutfitError,
    OutfitNotFoundError,
    OutfitStateError,
    activate_outfit,
    adopt_outfit_draft_image,
    adopt_outfit_regenerate_image,
    confirm_outfit,
    create_outfit_draft,
    delete_outfit,
    drain_outfit_descriptions,
    get_outfit_policy,
    list_outfits,
    prepare_outfit_prompt,
    prepare_outfit_regenerate_prompt,
    regenerate_outfit_draft,
    set_outfit_policy,
)
from .response_builders import (
    avatar_response,
    outfit_response,
)
from .scene_service import (
    SceneError,
    SceneLockedError,
    SceneNotFoundError,
    SceneQuotaExceededError,
    SceneStateError,
    activate_scene,
    adopt_scene,
    delete_scene,
    discard_scene,
    drain_scene_jobs,
    edit_scene_description,
    resume_scene_generation,
    resume_scene_jobs,
    retry_scene_description,
    schedule_initial_scene,
    schedule_scene_generation,
    schedule_scene_prompt,
    set_scene_policy,
)
from .video import (
    VideoPackError,
    VideoPackNotFoundError,
    VideoPackStateError,
    list_pack_responses,
)
from .video import (
    activate_pack as activate_video_pack,
)
from .video import (
    create_pack_from_clips as create_video_pack_from_clips,
)
from .video import (
    create_pack_from_reference as create_video_pack_from_reference,
)
from .video import (
    delete_pack as delete_video_pack,
)
from .video import drain_video_generation as drain_video_pack_generation
from .video import resume_processing_packs as resume_processing_video_packs
from .video import resume_video_generation_jobs as resume_video_generation_jobs
from .video import (
    retry_pack as retry_video_pack,
)
from .video_jobs import drain as drain_video_jobs
from .video_jobs import (
    enqueue_video_job,
    get_job,
    resume_pending_video_jobs,
)
from .visual_identity import load_self_visual_context, prepare_self_video_reference

__all__ = [
    "SceneError",
    "SceneLockedError",
    "SceneNotFoundError",
    "SceneQuotaExceededError",
    "SceneStateError",
    "activate_scene",
    "adopt_scene",
    "delete_scene",
    "discard_scene",
    "drain_scene_jobs",
    "edit_scene_description",
    "retry_scene_description",
    "resume_scene_generation",
    "resume_scene_jobs",
    "schedule_initial_scene",
    "schedule_scene_generation",
    "schedule_scene_prompt",
    "set_scene_policy",
    "load_self_visual_context",
    "prepare_self_video_reference",
    "drain_character_extractions",
    "resume_character_extractions",
    "schedule_character_extraction",
    "resume_initial_appearance",
    "ALLOWED_AVATAR_UPLOAD_MIME_TYPES",
    "AVATAR_JOB_LOCKS",
    "AvatarGenerationError",
    "AvatarNotFoundError",
    "AvatarSourceUnreadableError",
    "FullbodyGenerationError",
    "VideoPackError",
    "VideoPackNotFoundError",
    "VideoPackStateError",
    "ImageGenerationError",
    "ImageSealedError",
    "OutfitDraftExpiredError",
    "OutfitError",
    "OutfitNotFoundError",
    "OutfitStateError",
    "activate_video_pack",
    "create_video_pack_from_clips",
    "create_video_pack_from_reference",
    "retry_video_pack",
    "delete_video_pack",
    "list_pack_responses",
    "activate_outfit",
    "adopt_fullbody_seed",
    "adopt_avatar_seed",
    "prepare_avatar_prompt",
    "adopt_outfit_draft_image",
    "adopt_outfit_regenerate_image",
    "avatar_response",
    "compose_image_references",
    "confirm_fullbody_seed",
    "confirm_outfit",
    "create_outfit_draft",
    "delete_outfit",
    "drain_outfit_descriptions",
    "delete_portrait_file",
    "drain_video_jobs",
    "drain_video_pack_generation",
    "enqueue_video_job",
    "finalize_avatar",
    "generate_avatar",
    "generate_fullbody_reference",
    "generate_images",
    "get_active_avatar",
    "get_avatar_job_lock",
    "get_job",
    "get_outfit_policy",
    "list_avatar_history",
    "list_outfits",
    "load_avatar_bytes_as_data_uri",
    "normalize_avatar_url_to_bare",
    "outfit_response",
    "prepare_fullbody_prompt",
    "prepare_outfit_prompt",
    "prepare_outfit_regenerate_prompt",
    "raise_if_image_sealed",
    "re_sign_bare_path",
    "regenerate_avatar",
    "regenerate_avatar_from_image",
    "regenerate_outfit_draft",
    "resolve_image_gen_chain",
    "resolve_uploaded_avatar_path",
    "resume_pending_video_jobs",
    "resume_processing_video_packs",
    "resume_video_generation_jobs",
    "select_avatar",
    "set_outfit_policy",
]
