"""进程级运行时设施：配置、数据库、日志、任务托管、附件与维护态；对外 re-export。"""

from .ai_config import (
    CAPABILITY_SERVICES,
    AIConfig,
    AIConfigPublic,
    AIConfigUpdate,
    CapabilityCard,
    CapabilityCardUpdate,
    ProviderCard,
    ProviderCardUpdate,
)
from .attachments import attachment_root, session_dir
from .attachments import gc_session as attachments_gc_session
from .background import BackgroundTask, TaskBag
from .backoff import backoff_for_poll
from .config import SETTINGS, insecure_secret_settings
from .constants import (
    ATTACHMENT_DATA_URL_MAX_CHARS,
    ATTACHMENT_TYPE_IMAGE,
    ATTACHMENT_TYPE_VIDEO,
    ATTACHMENT_VIDEO_EXTENSIONS,
    ATTACHMENT_VIDEO_MAX_BYTES,
    CONTEXT_COMPRESSION_TEMPERATURE_DEFAULT,
    CONTEXT_SUMMARY_HEADROOM_FACTOR,
    DEFAULT_LANGUAGE,
    DEFAULT_SESSION_TITLE,
    JSON_RPC_VERSION,
    JSONRPC_INTERNAL_ERROR,
    JSONRPC_INVALID_PARAMS,
    JSONRPC_INVALID_REQUEST,
    JSONRPC_METHOD_NOT_FOUND,
    JSONRPC_PARSE_ERROR,
    JSONRPC_SLASH_BUSY,
    JSONRPC_SLASH_CONFIRM_REQUIRED,
    JSONRPC_SLASH_GENERIC,
    JSONRPC_TURN_BUSY,
    LLM_MAX_OUTPUT_TOKENS,
    LLM_RETRY_MIN_TIMEOUT,
    MAX_VOICE_DESIGN_PROMPT_CHARS,
    NIGHTLY_PLANNING_REASONING_EFFORT,
    REMOTE_ASSET_DOWNLOAD_MAX_BYTES,
    SCENE_DOWNLOAD_MAX_BYTES,
    SEARCH_INPUT_MAX_LEN,
    SESSION_HISTORY_PRE_BUFFER,
    SESSION_HISTORY_TRUNCATE_THRESHOLD,
    SESSION_PREVIEW_MAX_CHARS,
    SESSION_TO_GLOBAL_KEY_ALIASES,
    SQL_LIKE_ESCAPE_CHAR,
    STT_MAX_AUDIO_BYTES,
    SUPPORTED_LANGUAGES,
    TEMPERATURE_MAX,
    TEMPERATURE_MIN,
    TITLE_GENERATION_TEMPERATURE,
    TITLE_MAX_CHARS,
    TITLE_SNIPPET_MAX_CHARS,
    TOOL_CALL_ID_HEX_PREFIX_LEN,
    TTS_MAX_TEXT_CHARS,
    VIDEO_INLINE_MAX_PER_REQUEST,
)
from .correlation import (
    REQUEST_ID_HEADER,
    adopt_inbound,
    begin_local_scope,
    correlated_exception_response,
    correlation_id_middleware,
    new_request_id,
)
from .database import ENGINE, SESSION_LOCAL, DbSession, database_url, get_db, session_scope
from .functions import (
    apply_partial,
    approx_text_tokens,
    coerce_hour_0_23,
    coerce_int,
    coerce_non_negative_float,
    ensure_utc,
    format_day_marker,
    format_local_date_str,
    format_local_iso,
    format_time_anchor,
    is_time_context_text,
    parse_llm_json,
    resolve_language,
    resolve_prompt_text,
    safe_json_loads,
    strip_outer_code_fence,
    tool_error,
    utc_now,
)
from .hashing import sha256_hex, sha512_b64
from .logger import get_logger, set_request_user_id, setup_logging
from .network import download_capped, is_safe_outbound, safe_outbound_async_client, safe_outbound_async_transport
from .observability import (
    SCENE_FAILURES_TOTAL,
    SCENE_IMAGES_TOTAL,
    SCENE_LLM_TRIGGERS_TOTAL,
    render_metrics_response,
    rpc_metrics,
)
from .paid_calls import log_paid_call
from .redact import redact_sensitive_text
from .temp_files import cleanup_expired, get_file_path, owned_temp_files, save_file
from .temp_files import purge_user as purge_user_temp_files
from .timezone import parse_timezone
from .user_maintenance_runtime import (
    begin_user_request,
    cancel_user_tasks,
    clear_user_maintenance,
    drain_user_tasks,
    end_user_request,
    is_user_in_maintenance,
    mark_user_maintenance,
    track_user_task,
    user_maintenance_lock,
    wait_for_user_requests,
)

__all__ = [
    "AIConfig",
    "AIConfigPublic",
    "AIConfigUpdate",
    "ATTACHMENT_DATA_URL_MAX_CHARS",
    "ATTACHMENT_TYPE_IMAGE",
    "ATTACHMENT_TYPE_VIDEO",
    "ATTACHMENT_VIDEO_EXTENSIONS",
    "ATTACHMENT_VIDEO_MAX_BYTES",
    "CAPABILITY_SERVICES",
    "CapabilityCard",
    "CapabilityCardUpdate",
    "CONTEXT_COMPRESSION_TEMPERATURE_DEFAULT",
    "CONTEXT_SUMMARY_HEADROOM_FACTOR",
    "DEFAULT_LANGUAGE",
    "DEFAULT_SESSION_TITLE",
    "DbSession",
    "ENGINE",
    "JSONRPC_INTERNAL_ERROR",
    "JSONRPC_INVALID_PARAMS",
    "JSONRPC_INVALID_REQUEST",
    "JSONRPC_METHOD_NOT_FOUND",
    "JSONRPC_PARSE_ERROR",
    "JSONRPC_SLASH_BUSY",
    "JSONRPC_SLASH_CONFIRM_REQUIRED",
    "JSONRPC_SLASH_GENERIC",
    "JSONRPC_TURN_BUSY",
    "JSON_RPC_VERSION",
    "LLM_MAX_OUTPUT_TOKENS",
    "LLM_RETRY_MIN_TIMEOUT",
    "MAX_VOICE_DESIGN_PROMPT_CHARS",
    "NIGHTLY_PLANNING_REASONING_EFFORT",
    "REMOTE_ASSET_DOWNLOAD_MAX_BYTES",
    "REQUEST_ID_HEADER",
    "ProviderCard",
    "ProviderCardUpdate",
    "SCENE_DOWNLOAD_MAX_BYTES",
    "SCENE_FAILURES_TOTAL",
    "SCENE_IMAGES_TOTAL",
    "SCENE_LLM_TRIGGERS_TOTAL",
    "SEARCH_INPUT_MAX_LEN",
    "SESSION_LOCAL",
    "SESSION_PREVIEW_MAX_CHARS",
    "SESSION_HISTORY_PRE_BUFFER",
    "SESSION_HISTORY_TRUNCATE_THRESHOLD",
    "SESSION_TO_GLOBAL_KEY_ALIASES",
    "SETTINGS",
    "SQL_LIKE_ESCAPE_CHAR",
    "STT_MAX_AUDIO_BYTES",
    "SUPPORTED_LANGUAGES",
    "TEMPERATURE_MAX",
    "TEMPERATURE_MIN",
    "TITLE_GENERATION_TEMPERATURE",
    "TITLE_MAX_CHARS",
    "TITLE_SNIPPET_MAX_CHARS",
    "TOOL_CALL_ID_HEX_PREFIX_LEN",
    "TTS_MAX_TEXT_CHARS",
    "VIDEO_INLINE_MAX_PER_REQUEST",
    "BackgroundTask",
    "TaskBag",
    "adopt_inbound",
    "apply_partial",
    "approx_text_tokens",
    "attachment_root",
    "attachments_gc_session",
    "backoff_for_poll",
    "begin_local_scope",
    "begin_user_request",
    "cancel_user_tasks",
    "cleanup_expired",
    "clear_user_maintenance",
    "coerce_hour_0_23",
    "coerce_int",
    "coerce_non_negative_float",
    "correlated_exception_response",
    "correlation_id_middleware",
    "database_url",
    "download_capped",
    "drain_user_tasks",
    "end_user_request",
    "ensure_utc",
    "format_day_marker",
    "format_local_date_str",
    "format_local_iso",
    "format_time_anchor",
    "get_db",
    "get_file_path",
    "get_logger",
    "insecure_secret_settings",
    "is_safe_outbound",
    "is_time_context_text",
    "is_user_in_maintenance",
    "log_paid_call",
    "mark_user_maintenance",
    "new_request_id",
    "owned_temp_files",
    "parse_llm_json",
    "parse_timezone",
    "redact_sensitive_text",
    "render_metrics_response",
    "resolve_language",
    "purge_user_temp_files",
    "resolve_prompt_text",
    "rpc_metrics",
    "safe_json_loads",
    "strip_outer_code_fence",
    "safe_outbound_async_client",
    "safe_outbound_async_transport",
    "save_file",
    "session_dir",
    "session_scope",
    "set_request_user_id",
    "setup_logging",
    "sha256_hex",
    "sha512_b64",
    "tool_error",
    "track_user_task",
    "user_maintenance_lock",
    "utc_now",
    "wait_for_user_requests",
]
