"""动作源视频允许的编码尾差；交付片段仍受动作时长上限约束。"""

from modules.companion import ABSOLUTE_MAX_DURATION_SECONDS

SOURCE_DURATION_TOLERANCE_SECONDS = 1.5
MAX_ACTION_SOURCE_SECONDS = ABSOLUTE_MAX_DURATION_SECONDS + SOURCE_DURATION_TOLERANCE_SECONDS
